### PR TITLE
Fix Task<TResult>.TrySetResult(TResult result) method to set result after transition to Completed state but before sending signal about completion

### PR DESCRIPTION
**Pull request by gickis**
Fix issue #47

### CODE REVIEW

**Comment by skarllot** [comment]
I think that is better to call `AtomicStateUpdate` and `SendCompletedSignal` on `TrySetResult` method to avoid more allocations and reduce GC pressure.

**Comment by gickis** [comment]
But in this case, I will need to update these methods and make them protected. If you are ok with that - I will update PR.

**Comment by skarllot** [comment]
@gickis Its ok for me, I prefer `private protected` for this case to not allow other external derived types to access it.

**Comment by gickis** [comment]
@skarllot - done.

**Pull request merged**
